spring:
  application:
    name: robotmc-installer
  main:
    web-application-type: none

installer:
  minecraft:
    version: 1.21.11
  mod:
    loader:
      type: neo_forge
      version: 21.11.6-beta
      install-options:
        - '--install-client'
    mods:
      - download-url: 'https://cdn.modrinth.com/data/YL57xq9U/versions/Gbr8rEDk/iris-neoforge-1.10.2+mc1.21.11.jar'
      - download-url: 'https://cdn.modrinth.com/data/lfHFW1mp/versions/LU6sozZq/journeymap-neoforge-1.21.11-6.0.0-beta.53.jar'
      - download-url: 'https://cdn.modrinth.com/data/AANobbMI/versions/k5Rs4Eru/sodium-neoforge-0.8.0+mc1.21.11.jar'
  servers:
    - ip: minecraft.o-r.cc
      name: Robot Server
  resource-packs:
    - download-url: 'https://cdn.modrinth.com/data/r4GILswZ/versions/vyty9ijM/Faithful 64x - December 2025 Release.zip'
